### ISSUE TITLE
create header 

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/workshop-typescript-types-of-weather-team-breakfast-bap#1]
```[tasklist]
### Tasks
- [x] add logo on the top of the page
- [x] give it a h1 title Breakfast BAP Weather App
- [x] description of how to use the app
- [x] add styling to the header components
```
