### ISSUE TITLE
create main

### ISSUE THREAD

**Issue by peposlawa** [SchoolOfCode/workshop-typescript-types-of-weather-team-breakfast-bap#2]
```[tasklist]
### Tasks
- [x] add search bar
- [x] add submit button
- [x] section underneath the search bar to display the weather details
- [x] add styling to the components
```
